# Change these first
owner: JeffreyBool # Your GitHub username
repo: githubmemory-upptime # Your Github repository name

# Add your sites here
sites:
  - name: githubmemory
    url: https://githubmemory.com

status-website:
  cname: upptime.githubmemory.com
  #baseUrl: /githubmemory-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: githubmemory-upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: The website status can be monitored in real time
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
